sonar.projectKey=notes-app
sonar.projectName=Notes App
sonar.projectVersion=1.0

sonar.sources=api-gateway,notes-service,user-service,frontend
sonar.exclusions=**/node_modules/**,**/package-lock.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
